config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman-vs-superman'

  post 'pages/vot_batman'
  post 'pages/vot_superman'

  root 'pages#batman-vs-superman'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  layout "layout_experiments"

  def page1
    @defecto_regresiva = 300
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end

  def batman_vs_superman
  end

  def vot_batman
    Voto.create(email: params[:email], heroe:"batman")
    redirect_to pages_batman_path
  end

  def vot_superman
    Voto.create(email: params[:email], heroe:"superman")
    redirect_to pages_superman_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= experiments_page1_path %>">page1</a></li>
        <li><a href="<%= experiments_page2_path %>">page2</a></li>
        <li><a href="<%= experiments_page3_path %>">page3</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/experiments/page1.html.erb
<h1>Experiments page1</h1>
<h1>Cuenta Regresiva: <span id="numero" class="label label-danger"></span></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<script type="text/javascript">
  jQuery(document).on('turbolinks:load', function() {

    regresiva(<%= @defecto_regresiva %>);

  })
</script>

app/views/experiments/page2.html.erb
<h1>Experiments page2</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/experiments/page3.html.erb
<h1>Experiments page3</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:action]%>">
  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/layouts/layout_experiments.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>experiments</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body class='<%= "#{params[:controller]} #{params[:action]}" %>'>
  <%= render 'navbar' %>
  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/pages/batman.html.erb
<h1>I am Batman</h1>

app/views/pages/batman_vs_superman.html.erb
<div class="row">
  <div id="batman" class="col-xs-6">
    <div class="row">
      <div class="col-md-12 btn-group btn-group-justified">
        <a class="btn btn-primary" role="button" href=<%= asset_path(pages_batman_path) %>>ir a Batman</a>
      </div>
      <form class="col-md-12 form-inline" role="form" action=<%= pages_vot_batman_path %> method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group">
          <label class="sr-only" for="InputEmail">Email address</label>
          <input name="email" type="email" class="form-control" id="InputEmail" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Votar</button>
      </form>
    </div>
  </div>
  <div id="superman" class="col-xs-6">
    <div class="row">
      <div class="col-md-12 btn-group btn-group-justified">
        <a class="btn btn-primary" role="button" href=<%= asset_path(pages_superman_path) %>>ir a Superman</a>
      </div>
      <form class="col-md-12 form-inline" role="form" action=<%= pages_vot_superman_path %> method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group">
          <label class="sr-only" for="InputEmail">Email address</label>
          <input name="email" type="email" class="form-control" id="InputEmail" placeholder="Email">
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Votar</button>
      </form>
    </div>
  </div>
</div>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>